#pragma once
void Interface();
void set0();//管理员界面
void set1();//用户界面
void menu0();//管理员菜单
void menu1();//用户菜单
void Goods_menu();//商品管理菜单
void Customer_menu();//用户管理菜单
void Sort_menu();//功能菜单
void SortGoods_menu();//排序菜单
void static_menu();//统计菜单
//void Sort();
